---
- hosts: all 
  become: yes  
  tasks:
    - name: Update APT
      ansible.builtin.apt:
        update_cache: true

    - name: Install python
      ansible.builtin.package:
        name: python
        state: present

    - name: Install apache2
      ansible.builtin.package:
        name: apache2
        state: present

    - name: Copy apache2.conf
      ansible.builtin.copy:
        src: /home/daltonw_sloan/dwsloan42-csc2510-infrastructure/files/config/apache2.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: '0644'

    - name: Copy index.html
      ansible.builtin.copy:
        src: /home/daltonw_sloan/dwsloan42-csc2510-infrastructure/files/site/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Create a symbolic link
      ansible.builtin.file:
        src: /etc/apache2/mods-available/headers.load
        dest: /etc/apache2/mods-enabled/headers.load
        owner: root
        group: root
        state: link

    - name: Restart apache2
      ansible.builtin.service:
        name: apache2
        state: reloaded
